const redundantDictionary = {
	"a":[
		"(absolutely) necessary",
		"(absolutely) essential",
		"(actual) facts",
		"advance (forward)",
		"(advance) planning",
		"(advance) preview",
		"(advance) reservations",
		"(advance) warning",
		"add (an additional)",
		"add (up)",
		"(added) bonus",
		"(affirmative) yes",
		"(aid and) abet",
		"(all-time) record",
		"alternative (choice)",
		"A.M. (in the morning)",
		"(and) etc.",
		"(anonymous) stranger",
		"(annual) anniversary",
		"(armed) gunman",
		"(artificial) prosthesis",
		"ascend (up)",
		"ask (the question)",
		"assemble (together)",
		"attach (together)",
		"ATM (machine)",
		"autobiography (of his or her own life)"
	],
	"b":[
		"bald(-headed)",
		"balsa (wood)",
		"(basic) fundamentals",
		"(basic) necessities",
		"best (ever)",
		"biography (of his--or her--life)",
		"blend (together)",
		"(boat) marina",
		"bouquet (of flowers)",
		"brief (in duration)",
		"(brief) moment",
		"(brief) summary",
		"(burning) embers"
	],
	"c":[
		"cacophony (of sound)",
		"cameo (appearance)",
		"cancel (out)",
		"(careful) scrutiny",
		"cash (money)",
		"cease (and desist)",
		"circle (around)",
		"circulate (around)",
		"classify (into groups)",
		"(close) proximity",
		"(closed) fist",
		"collaborate (together)",
		"combine (together)",
		"commute (back and forth)",
		"compete (with each other)",
		"(completely) annihilate",
		"(completely) destroyed",
		"(completely) eliminate",
		"(completely) engulfed",
		"(completely) filled",
		"(completely) surround",
		"(component) parts",
		"confer (together)",
		"connect (together)",
		"connect (up)",
		"confused (state)",
		"consensus (of opinion)",
		"(constantly) maintained",
		"cooperate (together)",
		"could (possibly)",
		"crisis (situation)",
		"curative (process)",
		"(current) incumbent",
		"(current) trend"
	],
	"d":[
		"depreciate (in value)",
		"descend (down)",
		"(desirable) benefits",
		"(different) kinds",
		"disappear (from sight)",
		"drop (down)",
		"during (the course of)",
		"dwindle (down)"
	]
};