const redundantDictionary = {
	"eng": {
		"a": [
			"(absolutely) necessary",
			"(absolutely) essential",
			"(actual) facts",
			"advance (forward)",
			"(advance) planning",
			"(advance) preview",
			"(advance) reservations",
			"(advance) warning",
			"add (an additional)",
			"add (up)",
			"(added) bonus",
			"(affirmative) yes",
			"(aid and) abet",
			"(all-time) record",
			"alternative (choice)",
			"A.M. (in the morning)",
			"(and) etc.",
			"(anonymous) stranger",
			"(annual) anniversary",
			"(armed) gunman",
			"(artificial) prosthesis",
			"ascend (up)",
			"ask (the question)",
			"assemble (together)",
			"attach (together)",
			"ATM (machine)",
			"autobiography (of his or her own life)"
		],
		"b": [
			"bald(-headed)",
			"balsa (wood)",
			"(basic) fundamentals",
			"(basic) necessities",
			"best (ever)",
			"biography (of his--or her--life)",
			"blend (together)",
			"(boat) marina",
			"bouquet (of flowers)",
			"brief (in duration)",
			"(brief) moment",
			"(brief) summary",
			"(burning) embers"
		],
		"c": [
			"cacophony (of sound)",
			"cameo (appearance)",
			"cancel (out)",
			"(careful) scrutiny",
			"cash (money)",
			"cease (and desist)",
			"circle (around)",
			"circulate (around)",
			"classify (into groups)",
			"(close) proximity",
			"(closed) fist",
			"collaborate (together)",
			"combine (together)",
			"commute (back and forth)",
			"compete (with each other)",
			"(completely) annihilate",
			"(completely) destroyed",
			"(completely) eliminate",
			"(completely) engulfed",
			"(completely) filled",
			"(completely) surround",
			"(component) parts",
			"confer (together)",
			"connect (together)",
			"connect (up)",
			"confused (state)",
			"consensus (of opinion)",
			"(constantly) maintained",
			"cooperate (together)",
			"could (possibly)",
			"crisis (situation)",
			"curative (process)",
			"(current) incumbent",
			"(current) trend"
		],
		"d": [
			"depreciate (in value)",
			"descend (down)",
			"(desirable) benefits",
			"(different) kinds",
			"disappear (from sight)",
			"drop (down)",
			"during (the course of)",
			"dwindle (down)"
		],
		"e": [
			"each (and every)",
			"earlier (in time)",
			"eliminate (altogether)",
			"emergency (situation)",
			"(empty) hole",
			"empty (out)",
			"(empty) space",
			"enclosed (herein)",
			"(end) result",
			"enter (in)",
			"(entirely) eliminate",
			"equal (to one another)",
			"eradicate (completely)",
			"estimated at (about)",
			"evolve (over time)",
			"(exact) same",
			"(exposed) opening",
			"extradite (back)",
		],
		"f": [
			"(face) mask",
			"fall (down)",
			"(favorable) approval",
			"(fellow) classmates",
			"(fellow) colleague",
			"few (in number)",
			"filled (to capacity)",
			"(final) conclusion",
			"(final) end",
			"(final) outcome",
			"(final) ultimatum",
			"(first and) foremost",
			"(first) conceived",
			"first (of all)",
			"fly (through the air)",
			"follow (after)",
			"(foreign) imports",
			"(former) graduate",
			"(former) veteran",
			"(free) gift",
			"(from) whence",
			"(frozen) ice",
			"(frozen) tundra",
			"full (to capacity)",
			"(full) satisfaction",
			"fuse (together)",
			"(future) plans",
			"(future) recurrence",
		],
		"g": [
			"gather (together)",
			"(general) public",
			"GOP (party)",
			"GRE (exam)",
			"green [or blue or whatever] (in color)",
			"grow (in size)",
		],
		"h": [
			"had done (previously)",
			"(harmful) injuries",
			"(head) honcho",
			"heat (up)",
			"HIV (virus)",
			"hoist (up)",
			"(hollow) tube",
			"hurry (up)",
		],
		"i": [
			"(illustrated) drawing",
			"incredible (to believe)",
			"indicted (on a charge)",
			"input (into)",
			"integrate (together)",
			"integrate (with each other)",
			"interdependent (on each other)",
			"introduced (a new)",
			"introduced (for the first time)",
			"(ir)regardless",
			"ISBN (number)",
		],
		"j": [
			"join (together)",
			"(joint) collaboration",
		],
		"k": [
			"kneel (down)",
			"(knowledgeable) experts",
		],
		"l": [
			"lag (behind)",
			"later (time)",
			"LCD (display)",
			"lift (up)",
			"(little) baby",
			"(live) studio audience",
			"(live) witness",
			"(local) residents",
			"look (ahead) to the future",
			"look back (in retrospect)",
		],
		"m": [
			"made (out) of",
			"(major) breakthrough",
			"(major) feat",
			"manually (by hand)",
			"may (possibly)",
			"meet (together)",
			"meet (with each other)",
			"(mental) telepathy",
			"merge (together)",
			"might (possibly)",
			"minestrone (soup)",
			"mix (together)",
			"(mutual) cooperation",
			"(mutually) interdependent",
			"mutual respect (for each other)",
		],
		"n": [
			"nape (of her neck)",
			"(native) habitat",
			"(natural) instinct",
			"never (before)",
			"(new) beginning",
			"(new) construction",
			"(new) innovation",
			"(new) invention",
			"(new) recruit",
			"none (at all)",
			"nostalgia (for the past)",
			"(now) pending",
			"(number-one) leader in",
		],
		"o": [
			"off (of)",
			"(old) adage",
			"(old) cliche",
			"(old) custom",
			"(old) proverb",
			"(open) trench",
			"open (up)",
			"(oral) conversation",
			"(originally) created",
			"output (out of)",
			"(outside) in the yard",
			"outside (of)",
			"(over) exaggerate",
			"over (with)",
			"(overused) cliche",
		],
		"p": [
			"(pair of) twins",
			"palm (of the hand)",
			"(passing) fad",
			"(past) experience",
			"(past) history",
			"(past) memories",
			"(past) records",
			"penetrate (into)",
			"period (of time)",
			"(personal) friend",
			"(personal) opinion",
			"pick (and choose)",
			"PIN (number)",
			"pizza (pie)",
			"plan (ahead)",
			"plan (in advance)",
			"(Please) RSVP",
			"plunge (down)",
			"(polar) opposites",
			"(positive) identification",
			"postpone (until later)",
			"pouring (down) rain",
			"(pre)board (as an airplane)",
			"(pre)heat",
			"(pre)record",
			"(private) industry",
			"(present) incumbent",
			"present (time)",
			"previously listed (above)",
			"proceed (ahead)",
			"(proposed) plan",
			"protest (against)",
			"pursue (after)",
		],
		"q": [],
		"r": [
			"raise (up)",
			"RAM (memory)",
			"reason is (because)",
			"reason (why)",
			"recur (again)",
			"re-elect (for another term)",
			"refer (back)",
			"reflect (back)",
			"(regular) routine",
			"repeat (again)",
			"reply (back)",
			"retreat (back)",
			"revert (back)",
			"rise (up)",
			"round (in shape)",
		],
		"s": [
			"(safe) haven",
			"(safe) sanctuary",
			"same (exact)",
			"(sand) dune",
			"scrutinize (in detail)",
			"separated (apart from each other)",
			"(serious) danger",
			"share (together)",
			"(sharp) point",
			"shiny (in appearance)",
			"shut (down)",
			"(single) unit",
			"skipped (over)",
			"slow (speed)",
			"small (size)",
			"(small) speck",
			"soft (in texture) [or (to the touch)]",
			"sole (of the foot)",
			"spell out (in detail)",
			"spliced (together)",
			"start (off) or (out)",
			"(still) persists",
			"(still) remains",
			"(sudden) impulse",
			"(sum) total",
			"surrounded (on all sides)",
		],
		"t": [
			"tall (in height)",
			"tall (in stature)",
			"(temper) tantrum",
			"ten (in number)",
			"three a.m. (in the morning)",
			"(three-way) love triangle",
			"time (period)",
			"(tiny) bit",
			"(total) destruction",
			"(true) facts",
			"(truly) sincere",
			"tuna (fish)",
			"(twelve) noon or midnight",
			"(two equal) halves",
		],
		"u": [
			"(ultimate) goal",
			"undergraduate (student)",
			"(underground) subway",
			"(unexpected) emergency",
			"(unexpected) surprise",
			"(unintentional) mistake",
			"(universal) panacea",
			"(unnamed) anonymous",
			"UPC (code)",
			"(usual) custom",
		],
		"v": [
			"vacillate (back and forth)",
			"(veiled) ambush",
			"(very) pregnant",
			"(very) unique",
			"visible (to the eye)",
		],
		"w": [
			"(wall) mural",
			"warn (in advance)",
			"weather (conditions)",
			"weather (situation)",
			"whether (or not)",
			"(white) snow",
			"write (down)",
		],
		"x": [],
		"y": [],
		"z": []
	},
	"es": {
		"a": [],
		"b": [],
		"c": [],
		"d": [],
		"e": [],
		"f": [],
		"g": [],
		"h": [],
		"i": [],
		"j": [],
		"k": [],
		"l": [],
		"m": [],
		"n": [],
		"o": [],
		"p": [],
		"q": [],
		"r": [],
		"s": [],
		"t": [],
		"u": [],
		"v": [],
		"w": [],
		"x": [],
		"y": [],
		"z": []
	}
};